{% set name = "debtcollector" %}
{% set version = "1.17.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "71e3350b6b97acede200f30b3858749b21303a70fde4ded26e4cbe599a3b0466" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools
    - pbr >=2.0.0

  run:
    - python
    - pbr !=2.1.0,>=2.0.0
    - six >=1.9.0
    - wrapt >=1.7.0
    - funcsigs >=0.4  # [py26 or py27]

test:
  imports:
    - debtcollector
    - debtcollector.moves
    - debtcollector.renames
    - debtcollector.removals
    - debtcollector.fixtures

about:
  home: http://docs.openstack.org/developer/debtcollector/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: A collection of Python deprecation patterns and strategies that help you collect your technical debt in a non-destructive manner.
  dev_url: https://git.openstack.org/cgit/openstack/debtcollector
  doc_url: http://docs.openstack.org/developer/debtcollector/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
