# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "tp/j4aeb6/zHj+IFRIAalC0IOkv2AgArz8Lx8e1qSnrSD2ogsmKl7AW8/TFzHKOS3so/oCjnIT9PeYLW7CdzYGvxnSAp9y0XC0PwKy1Qzee/niQXGHbBYRWeTQKaGwrPTxJ4z16KwRONRsPx2OF6QNtf2+bzdAz6S5H7Da/zVBGDF+PYGkx+9k5vHJuRva+2kvbKTERcJMAXi6/dbjZXbUQsDQsKB7JN0UCfCRQRudBdmOzZ8ysDDlvDQrcNK5Nf+XDUbW4/xjJvASeTRoEk+sKtjClRIVC7ihOnyij2XrAexSwMDxNMGE75oFWYmtGlQWHmC4ay+A9yzlRlw929uQot0FIdaLuWaLZgCrVyB47Wm91x9SenN2s5V1RVVTAme3wjjvF633Xhujtd6k7x2gu32KBQzl0e9V2SZ6X8qGKyTPhwvZUwumshslIlikEclfvS3gLcaPIb3PX6Jkj+JiL37JQk3rJesSy3OGRzrpkXKPBfGDEegefrSFh/xjNxySjVXbpunYQBsHatokVWaaQZXKCYoRFhH1hbDHJtE2tufk0u5ErrEAH9YSjtoq65HfUKmy6sjHjOEPTlkl8bGF6oF1UAoTz4IqNKE9kjIS9/Ik2+YjhPEiDIs20TSH3TePr+nn953CfIUm1JZ2yRVyhPILT2F47VA54TwBEg/lc="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
