travis:
  secure:
    BINSTAR_TOKEN: tp/j4aeb6/zHj+IFRIAalC0IOkv2AgArz8Lx8e1qSnrSD2ogsmKl7AW8/TFzHKOS3so/oCjnIT9PeYLW7CdzYGvxnSAp9y0XC0PwKy1Qzee/niQXGHbBYRWeTQKaGwrPTxJ4z16KwRONRsPx2OF6QNtf2+bzdAz6S5H7Da/zVBGDF+PYGkx+9k5vHJuRva+2kvbKTERcJMAXi6/dbjZXbUQsDQsKB7JN0UCfCRQRudBdmOzZ8ysDDlvDQrcNK5Nf+XDUbW4/xjJvASeTRoEk+sKtjClRIVC7ihOnyij2XrAexSwMDxNMGE75oFWYmtGlQWHmC4ay+A9yzlRlw929uQot0FIdaLuWaLZgCrVyB47Wm91x9SenN2s5V1RVVTAme3wjjvF633Xhujtd6k7x2gu32KBQzl0e9V2SZ6X8qGKyTPhwvZUwumshslIlikEclfvS3gLcaPIb3PX6Jkj+JiL37JQk3rJesSy3OGRzrpkXKPBfGDEegefrSFh/xjNxySjVXbpunYQBsHatokVWaaQZXKCYoRFhH1hbDHJtE2tufk0u5ErrEAH9YSjtoq65HfUKmy6sjHjOEPTlkl8bGF6oF1UAoTz4IqNKE9kjIS9/Ik2+YjhPEiDIs20TSH3TePr+nn953CfIUm1JZ2yRVyhPILT2F47VA54TwBEg/lc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
