travis:
  secure:
    BINSTAR_TOKEN: YLZX14bn/bvUsJyTT7cXyvz8xjXVtFSXESNVUXwcWG9+axC6yMj9zEcQ9wZ0vs4jbLsZGMZOY1TdIvu2eU9pHjvbv+1DyJ8qp8lLhd+a2fppVqWOL2yw5SzkQREmuI+izDvRxaaviXaqsu60+FCQjP0vtzRao2RfJ8KSYElkZJp6z3P7C4sy7kySfQH3fqM+Y1ONMiXnkcrSgDqTIOA3UJ63PF4YjOoLEhHXgGact+Ykd1WKac+Bf+eXf9/9x+/54KiAnfyZoIfIZonZOxF51be3JtWKF16F/ZBHaD9r9Gqyu2zHoN4XAaqJ6uI07ACL1iSzmhGdfcf/AymUTfH6NDv9Rdh9aZlfJHH8iIwjaZnJacK9MiLsvcwvTeDfUl69U9CsTZp8cfBa2336dJLRKxEBAAHwFnaw7tPnb+J1EfcfbDw+1FqOUvIcs/AmZTTiU1QESQ5jfd530T/FAFzqIl9MgdCU+yDxYbMHrsrKuX10zENZBJPLBFN9aslTdib245YifgiK+BwrUhEnHuUkiysCwx6IAGFFP4yVUXPxXm4PweYL0T7XlBf8Jt/U3bbs4WGoM8v6x3KsGdKLWhb3XSVCjv5vGwu+VyqvOmFk/+zICcRsoUJFBU2m5iCzkk+++VrKMNRmUAwEmxz+eNEGfovQY51ewDbyodsxQ1hPiXs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
