travis:
  secure:
    BINSTAR_TOKEN: ByihKvzqUdgYDwj4lcvrPUkWCPsNJ/h+gfHDIYpm98GXA4etNm7ydLj1lj3/GfLrm9O8Jz3SklC1ENvPGXBwPAaZgUqYoWddYOaP/R9pEu1EOokBJySaTMk8qNadNCIZDXbNocyi5Q3oKSSzayMxwa7adcyCEKhCQiC6nHLG1uPavU36kByIDC9jqH41kJ8QzgXIDyL/mb0sShpQgGFKyOfxQg8d424wzqZNTDxxbiHAMr19AFB2Ei+t+eVyqQku9q6Ipm5X7DNqM/lkOfY1vvzCLwdPEMACfUhH31J0X5ZgiqaQaJrZVbS521A2SVxF6MvSTNfC8QNmpDSOm43tZJkty77xMCCmFiVviXHiAtctAWLMDOWAKjwmUvtM86IwrbrJhS6BC6KHjEwjt0351+it6RjzbSAcVramqIRsyFblTdpV7AsxgAKkmTPRQrDjOnWPvLe9GKXeIlAEFJSn1plmjSwXP7b58fWpx+V3dJkOeuSZ50+kJaEY+NsbOYJ+OwDafzTIBOhnuoup/a1YDBXFUmIXYqkwaU5oh+0nzpc29SEXzcxJiHycLS5S89odUqAe1e6UcqwhL+vTqtA+GmBFjs9WOBj4d6G8gOf/WL6giUDgvgiQVyJVt6gsniI+qQ+ErtPR2QlOKW1Uus8Px4Tzr3LnBaa04cv7o3Xw2nY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
