travis:
  secure:
    BINSTAR_TOKEN: JvdFG+KEcRk+swA9meuFZQ+4tdwqGycbE6d2S4m8WIHkc1SF60DVV1kFgzM/DMORuughxrXvjfw7TDTU8XHSCqaZHDiG9IMnVnk7yAUC+8gjreLxkv98A9NmE6Dy2GTIHvMCHDLnRnxrT9b2DA4lZGk9wucbYForKZNBQvfYUufPLz4SlrH0fLwv5yygq7frziKYBRFL3dKjpxFzuDHwQlgTVN6wnPH5WH/jToTCIAi6NA/UUWIMV1Bo1trPMIhBuP54W0gep3AilC8oknz2vJ5eH3+cng1+R3ZHArrN4u01uaAtz6HxATeP0S9VZso9QDePuIXyiQEiWPImPrSTUAKzQnmoL+UVLdDAEFX723RnC6zL5kZhCcpEhpOu1Ar4rCWfqXNK5CwdtJrYOUCfMDkW11i2OsSWO9NcD466ZVHJ2CkxiJXItXaSuXWQkffFeQITkaWXEt29qd5n4z+JPlz7XfxI+VPx0Wd4YDCl6haceIrJfYn4yqLYJHMSLNUVc6G3pOiM/SjvH2DH5f4YRHR7MXMaHgAkbylvK42gtYsc7isJ1Jl8/Yd9jBpauf4uE4I1Da4MmiPh4FDQYoNG35J7JcwhNn54of60iDv3EdZ73LAoH9wXdtS2oaGCmwIHFnrbzubNaW0xDsXd8NxoCneaHSNxSaaFh1UGK9739pU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
