travis:
  secure:
    BINSTAR_TOKEN: PrWR53jGCozG/KMvegU2JtjrOTgtSvebjD7qxDroa7koHkd83oAOHaKg3+d6aYa9JCM8cvHaWV0MRD6OWdSue8aLxdkmobbOf5xNiz/62eZyPSIrXD9tveUNTrgwekDXSzJZcdnSbiGzw37cAc4OIJ/Q7R6uJVtwdAMKLZBWFMDeNSVlQiLlNWdf7DLYsfhhff4CWMWNpTFNcwtvPv7hBFTh/eOdtulXwUKZsA4hYXQx72vWDhnS9Cgeqbs5p4GHLBEfeikE5vX8DQovohVYqlbPvNx4qFnn7Zq3VfFA8u1/VV3hmaxV27Qm9jBvmdsS32q5Q5jdM4MzmiQcd1aS/DVyUAp1rzmB+rFctClA4H+SqUwnHzEoz5Ktg6QUG1CAVdygG9bHHGKetwWaek5A4F3XiBkxTFe7Wc6tMRmoQ4ZHCgAq1fwTQDD/D08mc9vkUJdd/Xvqhb6wMlo+Hv3dC5pps6VElPsK+pTlbm+zCIr6txRv8rBuWhR5TilTSyIKd59gDGmdnS2ZrBVu+8atkw3X2IOOMfum8INy8i4k/jB5e531N1hzUAIFzGWiKClodZCXOnJeGpgHEGH2FcoB6P1NXTfSA8ubIGHJ4JbwmYd4JiwjrteMcZLBiZPHcYdPFaW1VTbSpZWWryUMVxY3JOHSxc1h8NuJyBUXNunEgLA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
